# ssrcloud 重命名
[[rename_node]]
match = "(.落地).(\d+).(HGC).(\d+).*"
replace = "[薯条][$3]$1$4"

[[rename_node]]
match = "(中港)((专线)?).(IPLC|IEPL).((\w)(\d+)?)((\s\d{1,}[MG]bps)?)"
replace = "[薯条][$4]$1专线$5"

[[rename_node]]
match = "(.*)(台湾).(游戏专线)"
replace = "[薯条][$3]$2"

[[rename_node]]
match = "(加拿大)(\s\d)(\s\d{1,}[MG]bps).(\d[x倍])"
replace = "[薯条]$1$2"

[[rename_node]]
match = "(台湾).?(电信|HiNet)((\s\d{1,})?)(\s\d{1,}[MG]bps).*(\d[x倍]|Netflix|Hulu|HBO|动画疯|TVB)((\s\w)?)"
replace = "[薯条][$2]$1$3$7[NF]"

[[rename_node]]
match = "(新加坡|美国).?(Legacy|Magic((.A)?)|标准|高级).*(IEPL)?.中继\s((\s?\w)(\d+)?).*"
replace = "[薯条][$2]$1$6[NF]"

[[rename_node]]
match = "(美国)(\d+)(\s\d{1,}[MG]bps)?.*(\d[x倍]|Netflix|Hulu|HBO|动画疯|TVB).(CN2).*"
replace = "[薯条][$5]$1$2"

[[rename_node]]
match = "(香港)(Azure)(\s\d{1,})(\s\d{1,}[MG]bps)"
replace = "[薯条][$2]$1$3"

[[rename_node]]
match = "(香港)(柴湾)(\s\d{1,}[MG]bps).(\w).*(\d[x倍]|Netflix|Hulu|HBO|动画疯|TVB).(东落地).(\d{1,}).*"
replace = "[薯条]$1$2$4-$6$7[NF]"

[[rename_node]]
match = "(中国).(加拿大).(IPLC|IEPL).*([a-zA-Z]\s?\d{1,})((\s\d{1,}[MG]bps)?)"
replace = "[薯条][$3]$2$4"

[[rename_node]]
match = "(中国).(加拿大|台湾|新加坡|日本|香港).(IPLC|(沪日)?IEPL).*([a-zA-Z]\s?\d{1,})((\s\d{1,}[MG]bps)?).*"
replace = "[薯条][$3]$2$5$6"

[[rename_node]]
match = "(回国).*(\b\w\d{1,})((\s\d{1,}[MG]bps)?).*(网易云).*"
replace = "[薯条]中国$2[$5]"

[[rename_node]]
match = "(美国)(\d{1,}).*"
replace = "[薯条]$1$2"

[[rename_node]]
match = "(香港).*(御金·国峯).(環球).*([a-zA-Z]\d{1,})"
replace = "[薯条][HGC]$1$2$4"

[[rename_node]]
match = "(香港).*(御金·国峯).(名氣通).*([a-zA-Z]\d{1,})"
replace = "[薯条][TGT]$1$2$4"

[[rename_node]]
match = "(澳门).*((\b\d{1,})\s([MG]bps)).*(\b\w{1,})"
replace = "[薯条]$1$5[$3$4]"

[[rename_node]]
match = "(沪港)\s(IEPL).*((N)et(f)lix).*(\b\w{1,})"
replace = "[薯条][$2]$1$6[\U$4$5]"